export const WORKPACK_OPERATION_STATUSES = Object.freeze(['NOT_STARTED', 'READY', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED']);
const STATUSES = new Set(WORKPACK_OPERATION_STATUSES);
export const WORKPACK_OPERATION_TYPES = Object.freeze(['MATERIAL_PREPARATION', 'CUTTING', 'EDGE_PREPARATION', 'FIT_UP', 'WELDING', 'NDT', 'DIMENSIONAL_INSPECTION', 'BLASTING', 'PAINTING', 'ASSEMBLY', 'LOAD_OUT', 'OTHER']);
function createId() { return globalThis.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`; }
export function normalizeWorkpackOperations(items = []) { return (Array.isArray(items) ? items : []).map((item, index) => ({ id: String(item?.id || createId()), sequence: Math.max(1, Number.parseInt(item?.sequence, 10) || index + 1), operationType: String(item?.operationType || 'OTHER'), title: String(item?.title || ''), responsible: String(item?.responsible || ''), plannedStartDate: String(item?.plannedStartDate || ''), plannedFinishDate: String(item?.plannedFinishDate || ''), actualStartDate: String(item?.actualStartDate || ''), actualFinishDate: String(item?.actualFinishDate || ''), plannedManHours: Math.max(0, Number(item?.plannedManHours) || 0), actualManHours: Math.max(0, Number(item?.actualManHours) || 0), status: STATUSES.has(item?.status) ? item.status : 'NOT_STARTED', notes: String(item?.notes || '') })).sort((a,b) => a.sequence-b.sequence); }
export function normalizeOperationSequences(items = []) { return normalizeWorkpackOperations(items).map((item, index) => ({ ...item, sequence: index + 1 })); }
export function createWorkpackOperation(input = {}, sequence = 1) { return normalizeWorkpackOperations([{ ...input, id: input.id || createId(), sequence }])[0]; }
export function moveWorkpackOperation(items = [], id, direction) { const operations = normalizeOperationSequences(items); const index = operations.findIndex((item) => item.id === id); const target = index + direction; if (index < 0 || target < 0 || target >= operations.length) return operations; const next = [...operations]; [next[index], next[target]] = [next[target], next[index]]; return next.map((item, sequence) => ({ ...item, sequence: sequence + 1 })); }
export function validateWorkpackOperation(input = {}) { const errors = []; const sequence = Number(input.sequence); if (!Number.isInteger(sequence) || sequence < 1) errors.push({ field: 'sequence', message: 'Sequence must be a positive integer.' }); if (!String(input.title || '').trim()) errors.push({ field: 'title', message: 'Title is required.' }); ['plannedManHours', 'actualManHours'].forEach((field) => { if (input[field] !== '' && (!Number.isFinite(Number(input[field])) || Number(input[field]) < 0)) errors.push({ field, message: 'Man-hours cannot be negative.' }); }); [['plannedStartDate', 'plannedFinishDate'], ['actualStartDate', 'actualFinishDate']].forEach(([start, finish]) => { if (input[start] && input[finish] && new Date(input[finish]) < new Date(input[start])) errors.push({ field: finish, message: 'Finish date cannot precede start date.' }); }); return errors; }
